server:
  port: 10000
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://192.168.222.129:3306/user_microservice?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
eureka:
  client:
    fetch-registry: true  #作为客户端注册
    register-with-eureka: true  #从eureka获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:30000/eureka  #,http://127.0.0.1:30001/eureka
  instance:
    prefer-ip-address: true  #优先使用ip地址注册到eureka
    lease-renewal-interval-in-seconds: 5 #服务续约（向eureka发送服务正在运行的信号）时间间隔
    lease-expiration-duration-in-seconds: 10 #服务失效时间

